### PR TITLE
Added GoogleForm vue component

### PR DESCRIPTION
**Pull request by SuperShadowPlay**
Basically what is says on the tin. The sign-up form is now displayed on the main page.

### CODE REVIEW

**Review by jaythomas — CHANGES_REQUESTED** [review]
Works as the tin advertises! Simple and elegant. Nice job following the subtle conventions of the other components (capitalized component name and filename, putting the template at the top of your vue file, etc.). 

One nitpick, the other files are using an indentation of 2 spaces but the GoogleForm component is using 4 spaces for indentation. Ecmascript convention is typically 2 spaces, but I have no strong feelings how many spaces we use for this codebase as long as it's consistent across all the files.

Again, indentation has no functional impact on code as you probably know. Just something developers do in their code for their own sanity and making code more legible.

**Comment by SuperShadowPlay** [comment]
Alright, I'll keep that in mind for the next time I'm back at the keyboard. Thanks for the feedback!

Edit: So apparently replying in email re-quotes the thread, removed that to declutter.

**Comment by SuperShadowPlay** [comment]
Alright, I just went through and replaced the tabs with two spaces. I also fixed up some of the styling as my phone didn't look so good with `max-width: 75%;`. 

I'm assuming after pushing to the cloud I don't have to reopen a new pull request so I just have to let you know that changes have been made.

**Review by jaythomas — APPROVED** [review]
Cool, thanks. By the way we can use media queries to set different widths for mobile devices versus desktop devices. We'll worry about that another time though.

**Comment by jaythomas** [comment]
Go ahead and try out the squash merge feature. Your two commits well appear as a single commit on master. We'll also get to see if AWS auto deploys.

**Pull request merged**
